// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxN1WI8Lpd16AoX6AQd1K2sj871QNH-zw',
    appId: '1:325418838593:web:6a18b635ff895dc21df4c0',
    messagingSenderId: '325418838593',
    projectId: 'shopbd-87f26',
    authDomain: 'shopbd-87f26.firebaseapp.com',
    storageBucket: 'shopbd-87f26.appspot.com',
    measurementId: 'G-6K8GGX1DK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKtoXsxAZyx7GGMQ1Zo8C--pummIbLRDA',
    appId: '1:325418838593:android:a8b43ddbc4ff5ca21df4c0',
    messagingSenderId: '325418838593',
    projectId: 'shopbd-87f26',
    storageBucket: 'shopbd-87f26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHvFpEXf7ERP3w3-VQC9AKsn9BJD6hN9U',
    appId: '1:325418838593:ios:a970fb7b5a2c61cc1df4c0',
    messagingSenderId: '325418838593',
    projectId: 'shopbd-87f26',
    storageBucket: 'shopbd-87f26.appspot.com',
    androidClientId: '325418838593-4oeuu8h3cmte6frmcv4ct34sgjkeqh72.apps.googleusercontent.com',
    iosClientId: '325418838593-6hjenhu5ain715t94hj3shqtaojanhr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bdShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHvFpEXf7ERP3w3-VQC9AKsn9BJD6hN9U',
    appId: '1:325418838593:ios:749560851574497a1df4c0',
    messagingSenderId: '325418838593',
    projectId: 'shopbd-87f26',
    storageBucket: 'shopbd-87f26.appspot.com',
    androidClientId: '325418838593-4oeuu8h3cmte6frmcv4ct34sgjkeqh72.apps.googleusercontent.com',
    iosClientId: '325418838593-0qp5n1k77l4d0umu4mdta944843ou6tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.bdShop.RunnerTests',
  );
}
